# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eth_events', '0004_auto_20171127_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemon',
            name='status',
            field=models.CharField(choices=[('EXECUTING', 'Normal execution'), ('HALTED', 'System halted, there was an error')], default='EXECUTING', max_length=9),
        ),
    ]
