# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eth_events', '0005_daemon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
