# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eth_events', '0007_auto_20171207_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemon',
            name='listener_lock',
            field=models.BooleanField(default=False),
        ),
    ]
