# Generated by Django 2.0.2 on 2018-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eth_events', '0008_daemon_listener_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemon',
            name='last_error_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
