# Generated by Django 2.1.7 on 2019-05-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_eth_events', '0009_daemon_last_error_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daemon',
            name='status',
        ),
    ]
