# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemon',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
    ]
